### ISSUE TITLE
25X040 flash chip identification failure

### ISSUE THREAD

**Issue by tantratron** [MacThings/g-flash#1]
I've purchased a CH431A programmer then installed its driver on my iMac (Mojave) from [https://github.com/YTEC-info/CH341A-Softwares/tree/main/Drivers](url)

The lastest G-flash version 1.0.6 does autodetect the CH431A but it will never get the Chip type when the grabbers are installed. 

This has been tested with three different boards (LCD driver based on RTD2660H processor which always use 25x040 flash SPI NOR memory)... see attached one screnshot

![PCB-800099-V9](https://github.com/user-attachments/assets/fe888cd3-cab4-4fad-92bf-b6194ab694d5)

**Comment by MacThings** [comment]
Updated from flashrom 1.2.0 to 1.4.0. Perhaps it works now. Get it here:

https://github.com/MacThings/g-flash/releases/tag/Flash

By the way .... 3rd party Drivers will not be used from flashrom.

**Comment by tantratron** [comment]
Thanks for the update but would it be possible build a G-flash version able to run with Mojave ?

The 1.4.0 version will not run (your new build requires MacOS 12.4 and above) so I will try later into another iMac under Monterey. Ideally if it could work with older MacOS would be great as you did with 1.2.0

Regarding 3rd party driver, could you point out to a valid driver because so far, I only found and used  from [https://github.com/YTEC-info/CH341A-Softwares/tree/main/Drivers/MAC](url)

**Comment by tantratron** [comment]
P.S. I've now run my home personal iMac under **Monterey** versus my lab iMac under **Mojave**, now it works fine thanks to your new version. If possible, it would be nice to have the 1.4.0 runable under Mojave or earlier versions, thank you.

![PCB-800099-V9-Monterey](https://github.com/user-attachments/assets/ce572067-af07-453e-ad51-210dd5f809ff)

**Comment by MacThings** [comment]
Nice that it now works. With Xcode 16.1 I'm not able to compile for 10.15.

**Comment by MacThings** [comment]
You could try to copy the "bin" Folder in the App Package to the old App Package. Perhaps that works.

**Comment by tantratron** [comment]
Ok many thanks for having re-opened the thread, your application which does GUI contained flashrom is really good plus probably the only one for MacOS. Many people who do flashrom and other MCU stuff might prefer older OS because the race to always newer OS can be sometimes problematic and preventing some operations on older PCB.

For the moment, I've downloaded both your ZIF or TAR version from [https://github.com/MacThings/g-flash/releases/tag/Flash](url) which were stored in your repo in 2022. I've run my Xcode 10.3 on your file G-Flash.xcodeproj but it says **The project at '/Users/ottoman/Downloads/g-flash-Flash/G-Flash.xcodeproj' cannot be opened because it is in a future Xcode project file format. Adjust the project format using a compatible version of Xcode to allow it to be opened by this version of Xcode.**

If you want, I can clone your project then later try uploading other Xcode from [https://xcodereleases.com/](url) or maybe you could tell me what needs to be modified in your project so it would run with older Xcode.

Do you remember what Xcode version did you when you created G-flash based on flashrom 1.2 or what prevents now using older Xcode to compile the flashrom 1.4

**Comment by MacThings** [comment]
I set the Project compatibility to Xcode 12.0 (Catalina) now. Less is not possible with Xcode 16.1.

I did not compile flashrom myself. Can´t get it to work. But I loaded the Stuff with "brew" which contains precompiled binaries. 

`brew fetch --force-bottle --arch all --os all libusb flashrom lsusb libftdi`

I only patched flashrom that it will run without installing dependencies in the System (it uses the relative path to the contents of "lib") if you look into the bin Folder. And I patched the pathes inside the Libs too. A little bit Butcher Like but it works. :D  For me its important that the people can run the stuff out of the box.

And I merged (lipo) the x86 and ARM Version of the files to Universal.
E.g.
`lipo bin_arm/flashrom bin_x86/flashrom -create -output bin/flashrom`

**Comment by tantratron** [comment]
Would it be possible for you to publish your Catalina source code release to ease my download local copy so I can try compiling with Xcode ?

**Comment by MacThings** [comment]
I updated the repo already. Simply pull it.

**Comment by tantratron** [comment]
Ok thanks so I've pull your repo then locally Xcode built (version 14.0.1) with my iMac. It shows 2 issues, please see attached screenshot

<img width="1454" alt="Xcode-compliging-G-flash" src="https://github.com/user-attachments/assets/25779a9a-e2c3-484a-9e18-7a53099201f5">

**Comment by MacThings** [comment]
Remove Sparkle. You don`t need it. Than it should work

![grafik](https://github.com/user-attachments/assets/34ca2fa5-ae9a-4a51-95a4-c774045803f6)

**Comment by tantratron** [comment]
Sparkle removed then it compiles but strange behaviour depending the MacOS but 2 remaining topics.

**Topic 1**: Still some warnings, see attached screenshot

**Topic 2**: With my iMac running under Monterey, it works fine and will read the target SPI memory. However with my iMac running under Mojave, it will say the pliers are not installed but will get get the chip model

Same application does launch wether Monterey or Mojave but with Mojave, it will not execute correctly the memory reading. It does identify memory model, the problem is somewhere else which is strange because same code.

<img width="1229" alt="Capture d’écran 2024-11-18 à 10 30 22" src="https://github.com/user-attachments/assets/c6054241-fed8-41b3-988e-ed8973eceece">

**Comment by MacThings** [comment]
Could be that the flasrlrom binaries are not 100% 10.14 compatible (brew said  Monterey). There is nothing what I can do here.

**Comment by tantratron** [comment]
Yes I think you might be correct, the issue could be on the BIN folder and LIB subfolder content depending on Mojave versus Monterey. I've copied only the BIN folder from both your november 2021 G-flash (based on 1.2 flashrom) and your november 2024 G-flash (based on your 1.4 flashrom update few days ago after I created the issue).

Then I use directly TERMINAL window respectively from both my iMac: one under Mojave and the other under Monterey. After this, I just launch the ./flashrom command, it will work or fail depending the build stating

dyld: Library not loaded: lib/libusb-1.0.0.dylib
 Reason: no suitable image found.  Did find:
	lib/libusb-1.0.0.dylib: cannot load 'libusb-1.0.0.dylib' (load command 0x80000034 is unknown)
	lib/libusb-1.0.0.dylib: stat() failed with errno=1
cannot load 'libusb-1.0.0.dylib' (load command 0x80000034 is unknown)
Abort trap: 6

Do you confirm that all the necessary files should be found in RESOURCES/BIN folder what ever version of flashrom ?

If yes, could you detail excatly how you did compile or BREW from the flashrom github, is it something you do before launching the Xcode compiler ?

Thanks
